version: '2'
networks:
  sc:
    driver: bridge

services:
    postgres:
        image: postgres:11.3
        restart: always
        ports:
          - "5432:5432"
        networks:
          - sc
    postgres-seed:
        image: postgres:11.3
        networks:
          - sc
        volumes:
          - ./data:/data
          - ./postgres-seed:/postgres-seed
        working_dir: /postgres-seed
        command: bash load-data.sh
        links:
            - postgres:postgres
        depends_on:
            - postgres
    message-broker:
        image: vsouza/sqs-local
        restart: always
        networks:
          - sc
        ports:
          - "9324:9324"
    user-event-seed:
        build: ./user-event
        networks:
          - sc
        volumes:
          - ./data:/data
        command: python data-seed.py
        links:
            - message-broker:messagebroker
        depends_on:
            - message-broker
    user-event:
        build: ./user-event
        restart: always
        networks:
          - sc
        command: python data-listen.py
        links:
            - message-broker:messagebroker
            - postgres:postgres
        depends_on:
            - message-broker
            - postgres
            - postgres-seed
            - user-event-seed
