version: '2'
networks:
  sc:
    driver: bridge

services:
    postgres:
        image: postgres:11.3
        restart: always
        ports:
          - "5432:5432"
        networks:
          - sc
    postgres-seed:
        image: postgres:11.3
        networks:
          - sc
        volumes:
          - ./data:/data
          - ./postgres-seed:/postgres-seed
        working_dir: /postgres-seed
        command: bash load-data.sh
        links:
            - postgres:postgres
        depends_on:
            - postgres
